server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: dbuser
    password: dbpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: admin
      password: admin123